### ISSUE TITLE
翻译推荐

### ISSUE THREAD

**Issue by Demoonhusky** [solael/GrimDawnZH#58]
本着直译，忠于词义，不扭曲词义的理念，考究许久的总结。

===========================
审判官角色组合
===========================
Inquisitor + 
Soldier = Tactican
Demolitionist = Purifier
Occulist = Deceiver
Nightblade = Infiltrator
Arcanist = Mage Hunter
Shaman = Vindicator
Necromancer = Apostate
审判 + 战士 = 【战术家】
审判 + 爆破 = 【净化者】
审判 + 神秘 = 【欺诈者】 
审判 + 夜刃 = 【潜伏者】
审判 + 奥术 = 【魔法猎人】
审判 + 萨满 = 【维护者】  
审判 + 死灵 = 【反叛者】 
===========================
死灵法师角色组合
===========================
Necromancer + 
Soldier = Death Knight
Demolitionist = Defiler
Occulist = Cabalist
Nightblade = Reaper
Arcanist = Spell Binder
Shaman = Ritualist
Inquisitor = Apostate
死灵法+ 
战士 = 【死亡骑士】
死灵法+ 爆破 = 【污染者】
死灵法+ 神秘 = 【秘术师】
死灵法+ 夜刃 = 【收割者】
死灵法+ 奥术 = 【缚法者】  参考魔兽世界缚法者spell binder
死灵法+ 萨满 = 【祭祀者】
===========================
===========================
【审判】技能篇，数字顺序为从左向右递推
===========================
1.Ranged Expertise【远程专家】
2.Bursting Round【爆裂弹药】
3.Chilling Rounds【冻结弹药】
4.Storm Spread【风暴散射】
5.Word of Renewal【重生之语】
6.Vigor【活力】
7.Steel Resolve【钢铁决心】
8.Word of Arms【武器之语】
9.Aura of Conviction【信念光环】
10.Word of Pain【疼痛之语】
11.Word of Agony【痛苦之语】
12.Death Sentence【死刑】
13.Horn of Gandarr【甘达尔号角】
14.Flames of Ignaffar 【伊格纳法之焰】
15.Intensify 【增强】
16.Infernal Purge【地狱肃清】
17.Endless Flame【无尽之焰】
18.Tainted Flame【污染之焰】
19.Rune of Hagarrad【哈格拉符文】
20.Biting Cold【凛冽】
21.Chillsurge【寒潮】 
22.Chillsurge【谴责光环】
23.Storm Box of Elgoloth 【艾尔格洛斯的风暴之盒】
24.Lightning Tether【闪电链】
25.Allagast's Arcane Net【阿拉加斯特的神秘织网】
26.Inquisitor Seal【审判秘印】
27.Arcane Empowerment【奥术强化】
28.Null Field【空无之境】 
29.Deadly Aim【致命瞄准】
30.Rune of Kalastor【卡拉斯特符文】
31.Ignition【引燃】
32.Artefact Handling【工艺处理】

===========================
【死灵】技能篇，数字顺序为从左向右递推
===========================
1.Reaping Strike【收割打击】
2.Necrotic Edge【坏死刀锋】
3.Siphon Souls 【灵魂虹吸】
4.Blood Boil【沸腾之血】
5.Sear Soul【灵魂灼烧】
6.Drain Essence【吸取精华】
7. Hungering Reach【饥渴之触】
8.Decomposition【腐化】
9.Gravechill【黄泉颤抖】 
10.Harbinger of Souls【灵魂先驱】
11.Ravenous Earth【贪婪大地】
12.Decay【衰变】
13.Foul Eruption【腐臭喷发】
14.Bone Harvest【骨刺收割】
15.Terror【恐惧】
16.Soul Harvest【灵魂收割】
17.Harvester of Death【死亡收割】
18.Reap Spirit【精神收割】
19.Raise Skeletons【召唤骷髅】
20.Undead Legion【不死军团】
21.Will of the Crypt【墓穴意志】
22.Ill Omen【不祥预兆】
23.Summon Blight Fiend【召唤疫病恶魔】
24.Rotting Fumes【腐烂气息】
25.Blight Burst【疫病爆发】
26.Unstable Anomaly【不稳定畸变】
27.Master of Death 【死亡主宰】
28.Spectral Binding【幽灵结合】
29.Spectral Wrath【幽灵之怒】
30.Call of the Grave【坟墓召唤】
31.Mark of Torment【痛苦印记】
===========================
===========================
【星座篇】
===========================
1.Alladrah's Phoenix 【阿拉德拉的凤凰】
2.Attak Seru,the Mirage【阿塔克瑟如 幻影】 
3.Bard's Harp【吟游诗人的竖琴】
4.Ishtak,the Spring Maiden【伊师塔 春之少女】
5.Murmur,Mistress of Rumors【低语，情妇的谣言】
6.Quill【羽毛笔】
7.Rattosh the Veilwarden【莱托什 暗影守卫】
8.Staff of Rattosh【莱托什权杖】
9.Stag【雄鹿】
10.Toad【蟾蜍】
11.Typhos,the Jailor of Souls【堤丰灵魂狱卒】
12.Ultos,Shepherd of Storms【尤尔托斯牧羊人风暴】
13.Vire,the Stone Matron【维尔 石夫人 】
14.Wretch【不幸者】
===========================

**Comment by solael** [comment]
Nice！会加进资料片的汉化里面，如果你想开始资料片汉化，我可以把文本的给你。

**Comment by Demoonhusky** [comment]
我希望加入汉化。
demoonhusky@163.com，
这是我的邮箱。

**Comment by solael** [comment]
已经把你的账号加入 GrimDawnX 和 GrimDawnZHX 两个仓库，第一个是英文原文，第二个是中文版。我已经把新的文件和改动加入了中文版里面，如果你发现有遗漏可以继续加进去。

**Comment by solael** [comment]
每次更新都可以点commits查看

**Comment by solael** [comment]
建议用notepad++编辑txt，编码记得用utf-8 无bom。如果你不习惯用github更新可以把文件发给我我来上传。我的qq是439302911

**Comment by Demoonhusky** [comment]
我账户内没有看到GrimDawnX 和 GrimDawnZHX 两个仓库

**Comment by solael** [comment]
https://github.com/solael/GrimDawnX

**Comment by solael** [comment]
https://github.com/solael/GrimDawnZHX

**Comment by OStoneO** [comment]
使用汉化以后，游戏进入页面卡死会是什么原因造成的呢

**Comment by solael** [comment]
官方的锅，跟汉化没关系。官方提供的内置cjk字体用dx11模式渲染有问题

**Comment by solael** [comment]
已经加你qq，等会儿拉你进汉化群

**Comment by OStoneO** [comment]
请问，这个问题有解决方案吗?难道只能等官方修复BUG？
