### ISSUE TITLE
一些对话出现文本错位

### ISSUE THREAD

**Issue by wxz97121** [solael/GrimDawnZH#59]
http://tieba.baidu.com/photo/p?kw=%E6%81%90%E6%80%96%E9%BB%8E%E6%98%8E&flux=1&tid=5287135727&pic_id=55e0f81fbe096b63e6a2af8e06338744e9f8acdf&pn=1&fp=2&see_lz=1&red_tag=q3192874111

看到贴吧这个帖子意识到不是我一个人出现了这个问题？请问为什么会出现这个问题呢？

**Comment by solael** [comment]
你有没有买dlc？

**Comment by wxz97121** [comment]
没买Orzzzz

**Comment by solael** [comment]
没买的话现在是会出这种问题，官方知道也懒得管

**Comment by wxz97121** [comment]
好的……感谢QAQ
